### ISSUE TITLE
Linux Bounce - Serial port communications issue

### ISSUE THREAD

**Issue by dannystaple** [orionrobots/Bounce#51]
Upon attempts to use the Bounce Linux package - a serial port was not detected.

**Comment by dannystaple** [comment]
Now tested and verified working. It needed the same rebuild as windows. Need to try a downloaded package from CI (it works with npm source).

**Comment by airween** [comment]
Grabbed the latest version from here for Linux - but the issue above is still exists. Bounce doesn't realize the serial port.
Source: https://github.com/orionrobots/Bounce/releases
Version: 1.4.15

**Comment by dannystaple** [comment]
Can you attempt on the most recent Linux version? Also - if it fails, would it be possible to show me where the port actually is (lsusb, or /dev/tty...)? There is also debug available - Help->Toggle Developer Tools->Console, which should reveal how it is failing.

Thanks

**Comment by airween** [comment]
I'm using Linux Mint 17.2 (at home - later I'll check on my working laptop, that runs Mint 18.1).
The board has the Lua firmware:
```
$ minicom -D /dev/ttyUSB1
...
> print(_VERSION)
Lua 5.1
> print("hello world");
hello world

```
In the console there are some errors:

```
Uncaught Error: Module version mismatch. Expected 50, got 48. bindings.js:88
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). bounce_window.html:1
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). bounce_window.html:1
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). bounce_window.html:1
```

Thanks for your help!

a.

**Comment by dannystaple** [comment]
Can you try the most recent image? I've uploaded a new one with the rebuild so the version matches.
Also worth noting (I'm yet to add it to help somewhere) is that your user will probably need to be in the dialup group to have serial port access permission

**Comment by airween** [comment]
Thanks - I'll check it soon.
Of course, I'm member of dialup group - otherwise I couldn't access these devices. But as you can see, I can use it through minicom, and can upload the firmware (with my regular user).

Thanks,
a.

**Comment by airween** [comment]
I'm sorry, I can't find the binary .zip for Linux here:
https://github.com/orionrobots/Bounce/releases
The last version pushed 4 days ago - I think I have that.

**Comment by dannystaple** [comment]
There should definitely be a working binary zip in the most recent version.

**Comment by airween** [comment]
Could you upload a binary package for Linux too?

**Comment by dannystaple** [comment]
The .appimage file is a binary for linux. I should mention in the instructions.

**Comment by airween** [comment]
Hi Danny,
many thanks for your help - it works as well.

Regards,
a.

**Comment by dannystaple** [comment]
Fantastic - let me know if you have any further issues, suggestions or comments.
